#!/bin/bash

# imaging file
src="https://pbetneudataqhsqwvx.blob.core.windows.net/mclab/2P/$1"
dest="$5/2p.tif"
echo "~/azcopy_linux_amd64_10.16.1/azcopy cp src '/data/metafile_vgp.csv'"

# behav files
src="https://pbetneudataqhsqwvx.blob.core.windows.net/mclab/2P/$2"
dest="$6/2p.tif"

echo "Analysing files from $1"

echo "$6"